// Generated by gencpp from file vehicle_msgs/ControlSignal.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_CONTROLSIGNAL_H
#define VEHICLE_MSGS_MESSAGE_CONTROLSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Bool.h>
#include <vehicle_msgs/State.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct ControlSignal_
{
  typedef ControlSignal_<ContainerAllocator> Type;

  ControlSignal_()
    : header()
    , acc(0.0)
    , steer_rate(0.0)
    , is_openloop()
    , state()  {
    }
  ControlSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acc(0.0)
    , steer_rate(0.0)
    , is_openloop(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _acc_type;
  _acc_type acc;

   typedef double _steer_rate_type;
  _steer_rate_type steer_rate;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _is_openloop_type;
  _is_openloop_type is_openloop;

   typedef  ::vehicle_msgs::State_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::vehicle_msgs::ControlSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::ControlSignal_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSignal_

typedef ::vehicle_msgs::ControlSignal_<std::allocator<void> > ControlSignal;

typedef boost::shared_ptr< ::vehicle_msgs::ControlSignal > ControlSignalPtr;
typedef boost::shared_ptr< ::vehicle_msgs::ControlSignal const> ControlSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::ControlSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::ControlSignal_<ContainerAllocator1> & lhs, const ::vehicle_msgs::ControlSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acc == rhs.acc &&
    lhs.steer_rate == rhs.steer_rate &&
    lhs.is_openloop == rhs.is_openloop &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::ControlSignal_<ContainerAllocator1> & lhs, const ::vehicle_msgs::ControlSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ControlSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ControlSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ControlSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8714632b2f2dd9804baa230415c4a66e";
  }

  static const char* value(const ::vehicle_msgs::ControlSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8714632b2f2dd980ULL;
  static const uint64_t static_value2 = 0x4baa230415c4a66eULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/ControlSignal";
  }

  static const char* value(const ::vehicle_msgs::ControlSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 acc\n"
"float64 steer_rate\n"
"\n"
"# if open_loop is set, use the state as desired state \n"
"# and omit the control loop\n"
"std_msgs/Bool is_openloop\n"
"State state\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
"================================================================================\n"
"MSG: vehicle_msgs/State\n"
"Header header\n"
"geometry_msgs/Point vec_position\n"
"float64 angle\n"
"float64 curvature\n"
"float64 velocity\n"
"float64 acceleration\n"
"float64 steer\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vehicle_msgs::ControlSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acc);
      stream.next(m.steer_rate);
      stream.next(m.is_openloop);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::ControlSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::ControlSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acc: ";
    Printer<double>::stream(s, indent + "  ", v.acc);
    s << indent << "steer_rate: ";
    Printer<double>::stream(s, indent + "  ", v.steer_rate);
    s << indent << "is_openloop: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.is_openloop);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::vehicle_msgs::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_CONTROLSIGNAL_H
