// Generated by gencpp from file vehicle_msgs/FreeState.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_FREESTATE_H
#define VEHICLE_MSGS_MESSAGE_FREESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct FreeState_
{
  typedef FreeState_<ContainerAllocator> Type;

  FreeState_()
    : header()
    , pos()
    , vel()
    , acc()
    , angle(0.0)  {
    }
  FreeState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)
    , vel(_alloc)
    , acc(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _vel_type;
  _vel_type vel;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _acc_type;
  _acc_type acc;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::vehicle_msgs::FreeState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::FreeState_<ContainerAllocator> const> ConstPtr;

}; // struct FreeState_

typedef ::vehicle_msgs::FreeState_<std::allocator<void> > FreeState;

typedef boost::shared_ptr< ::vehicle_msgs::FreeState > FreeStatePtr;
typedef boost::shared_ptr< ::vehicle_msgs::FreeState const> FreeStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::FreeState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::FreeState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::FreeState_<ContainerAllocator1> & lhs, const ::vehicle_msgs::FreeState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.acc == rhs.acc &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::FreeState_<ContainerAllocator1> & lhs, const ::vehicle_msgs::FreeState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::FreeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::FreeState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::FreeState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::FreeState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::FreeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::FreeState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::FreeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a43acf62d3dbbd642cefa9d1fbe6fe0";
  }

  static const char* value(const ::vehicle_msgs::FreeState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a43acf62d3dbbd6ULL;
  static const uint64_t static_value2 = 0x42cefa9d1fbe6fe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::FreeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/FreeState";
  }

  static const char* value(const ::vehicle_msgs::FreeState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::FreeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"geometry_msgs/Point pos\n"
"geometry_msgs/Point vel\n"
"geometry_msgs/Point acc\n"
"\n"
"float64 angle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vehicle_msgs::FreeState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::FreeState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.acc);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::FreeState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::FreeState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
    s << indent << "acc: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.acc);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_FREESTATE_H
