// Generated by gencpp from file vehicle_msgs/LaneNet.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_LANENET_H
#define VEHICLE_MSGS_MESSAGE_LANENET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vehicle_msgs/Lane.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct LaneNet_
{
  typedef LaneNet_<ContainerAllocator> Type;

  LaneNet_()
    : header()
    , lanes()  {
    }
  LaneNet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lanes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vehicle_msgs::Lane_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vehicle_msgs::Lane_<ContainerAllocator> >::other >  _lanes_type;
  _lanes_type lanes;





  typedef boost::shared_ptr< ::vehicle_msgs::LaneNet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::LaneNet_<ContainerAllocator> const> ConstPtr;

}; // struct LaneNet_

typedef ::vehicle_msgs::LaneNet_<std::allocator<void> > LaneNet;

typedef boost::shared_ptr< ::vehicle_msgs::LaneNet > LaneNetPtr;
typedef boost::shared_ptr< ::vehicle_msgs::LaneNet const> LaneNetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::LaneNet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::LaneNet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::LaneNet_<ContainerAllocator1> & lhs, const ::vehicle_msgs::LaneNet_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lanes == rhs.lanes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::LaneNet_<ContainerAllocator1> & lhs, const ::vehicle_msgs::LaneNet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::LaneNet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::LaneNet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::LaneNet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a734ebfa710ee42bc06c0cc48ba9964";
  }

  static const char* value(const ::vehicle_msgs::LaneNet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a734ebfa710ee42ULL;
  static const uint64_t static_value2 = 0xbc06c0cc48ba9964ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/LaneNet";
  }

  static const char* value(const ::vehicle_msgs::LaneNet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Lane[] lanes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/Lane\n"
"Header header\n"
"\n"
"int32 id\n"
"int32 dir\n"
"\n"
"int32[] child_id\n"
"int32[] father_id\n"
"\n"
"int32 l_lane_id\n"
"bool l_change_avbl\n"
"\n"
"int32 r_lane_id\n"
"bool r_change_avbl\n"
"\n"
"string behavior\n"
"\n"
"float32 length\n"
"\n"
"geometry_msgs/Point start_point\n"
"geometry_msgs/Point final_point\n"
"\n"
"geometry_msgs/Point[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vehicle_msgs::LaneNet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lanes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneNet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::LaneNet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::LaneNet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lanes[]" << std::endl;
    for (size_t i = 0; i < v.lanes.size(); ++i)
    {
      s << indent << "  lanes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vehicle_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "    ", v.lanes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_LANENET_H
