// Generated by gencpp from file vehicle_msgs/ObstacleSet.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_OBSTACLESET_H
#define VEHICLE_MSGS_MESSAGE_OBSTACLESET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vehicle_msgs/CircleObstacle.h>
#include <vehicle_msgs/PolygonObstacle.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct ObstacleSet_
{
  typedef ObstacleSet_<ContainerAllocator> Type;

  ObstacleSet_()
    : header()
    , obs_circle()
    , obs_polygon()  {
    }
  ObstacleSet_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obs_circle(_alloc)
    , obs_polygon(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::vehicle_msgs::CircleObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vehicle_msgs::CircleObstacle_<ContainerAllocator> >::other >  _obs_circle_type;
  _obs_circle_type obs_circle;

   typedef std::vector< ::vehicle_msgs::PolygonObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vehicle_msgs::PolygonObstacle_<ContainerAllocator> >::other >  _obs_polygon_type;
  _obs_polygon_type obs_polygon;





  typedef boost::shared_ptr< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleSet_

typedef ::vehicle_msgs::ObstacleSet_<std::allocator<void> > ObstacleSet;

typedef boost::shared_ptr< ::vehicle_msgs::ObstacleSet > ObstacleSetPtr;
typedef boost::shared_ptr< ::vehicle_msgs::ObstacleSet const> ObstacleSetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::ObstacleSet_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::ObstacleSet_<ContainerAllocator1> & lhs, const ::vehicle_msgs::ObstacleSet_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.obs_circle == rhs.obs_circle &&
    lhs.obs_polygon == rhs.obs_polygon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::ObstacleSet_<ContainerAllocator1> & lhs, const ::vehicle_msgs::ObstacleSet_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64fa1aba570dc974a6d7fcb2a16d7851";
  }

  static const char* value(const ::vehicle_msgs::ObstacleSet_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64fa1aba570dc974ULL;
  static const uint64_t static_value2 = 0xa6d7fcb2a16d7851ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/ObstacleSet";
  }

  static const char* value(const ::vehicle_msgs::ObstacleSet_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"CircleObstacle[] obs_circle\n"
"PolygonObstacle[] obs_polygon\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/CircleObstacle\n"
"Header header\n"
"\n"
"int32 id\n"
"Circle circle\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/Circle\n"
"geometry_msgs/Point center\n"
"float32 radius\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/PolygonObstacle\n"
"Header header\n"
"\n"
"int32 id\n"
"geometry_msgs/Polygon polygon\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::vehicle_msgs::ObstacleSet_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obs_circle);
      stream.next(m.obs_polygon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleSet_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::ObstacleSet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::ObstacleSet_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obs_circle[]" << std::endl;
    for (size_t i = 0; i < v.obs_circle.size(); ++i)
    {
      s << indent << "  obs_circle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vehicle_msgs::CircleObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obs_circle[i]);
    }
    s << indent << "obs_polygon[]" << std::endl;
    for (size_t i = 0; i < v.obs_polygon.size(); ++i)
    {
      s << indent << "  obs_polygon[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vehicle_msgs::PolygonObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obs_polygon[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_OBSTACLESET_H
