(cl:in-package vehicle_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          DIR-VAL
          DIR
          CHILD_ID-VAL
          CHILD_ID
          FATHER_ID-VAL
          FATHER_ID
          L_LANE_ID-VAL
          L_LANE_ID
          L_CHANGE_AVBL-VAL
          L_CHANGE_AVBL
          R_LANE_ID-VAL
          R_LANE_ID
          R_CHANGE_AVBL-VAL
          R_CHANGE_AVBL
          BEHAVIOR-VAL
          BEHAVIOR
          LENGTH-VAL
          LENGTH
          START_POINT-VAL
          START_POINT
          FINAL_POINT-VAL
          FINAL_POINT
          POINTS-VAL
          POINTS
))